### ISSUE TITLE
Some questions about the new Navigation APIs

### ISSUE THREAD

**Issue by LiYanan2004** [NilCoalescing/SwiftUI-Code-Examples#3]
How can I back support iOS 14, iOS 15 while preserve the new functionality introduced this year through the new APIs, I mean, Is these APIs back supported? OR they can only work on iOS 16?

**Comment by nataliapanferova** [comment]
Unfortunately, the new navigation APIs are only available in iOS 16. On older iOS versions we still need to use the old NavigationView APIs.

**Comment by LiYanan2004** [comment]
Okay, thanks for replying. But I do hope these new APIs are backward compatible😁
